#!/bin/sh
##
#$ -S /bin/bash
#$ -cwd
#$ -N BME5320_blast_array
#$ -o $JOB_NAME.log
#$ -e $JOB_NAME.err
#$ -M robert-marini@uiowa.edu
#$ -m bes
#$ -q DK
#$ -pe smp 4 #2

CMD='./run_blast.sh ../data/faa-split/file$SGE_TASK_ID.faa'
echo "commands=$CMD ../data/faa-split/file$SGE_TASK_ID.faa"
./run_blast.sh ../data/faa-split/file$SGE_TASK_ID.faa


echo "****************"
date
#########################################
