#!/bin/sh
##
#$ -S /bin/bash
#$ -cwd
#$ -N blast_array
#$ -o $JOB_NAME.log
#$ -e $JOB_NAME.err
#$ -M robert-marini@uiowa.edu
#$ -m bes
#$ -q all.q,COE,UI,DK,INFORMATICS #DK,COE,UI #using sandbox queue for dev only!
#$ -pe smp 4 #2

NUM_CORES=4

CMD='./run_blast.sh ../data/faa-split/file$SGE_TASK_ID.faa'
echo "commands=$CMD ../data/faa-split/file$SGE_TASK_ID.faa"
./run_blast.sh ../data/faa-split/file$SGE_TASK_ID.faa $NUM_CORES


echo "****************"
date
#########################################
